import { useState, useEffect, useContext } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { AppContext } from '../context/AppContext';
import Loader from '../components/Loader';
import CardHolder from '../components/cards/CardHolder';
import { DragDropContext } from 'react-beautiful-dnd';
import { Box, SimpleGrid } from '@chakra-ui/react';

export default function Home() {
  const router = useRouter();
  const { loading, isAuthenticated, updateCard, cards } =
    useContext(AppContext);

  const [cards0, setCards0] = useState([]);
  const [cards1, setCards1] = useState([]);
  const [cards2, setCards2] = useState([]);
  const [cards3, setCards3] = useState([]);

  useEffect(() => {
    setCards0(cards?.filter((item) => item?.row === '0'));
    setCards1(cards?.filter((item) => item?.row === '1'));
    setCards2(cards?.filter((item) => item?.row === '2'));
    setCards3(cards?.filter((item) => item?.row === '3'));
  }, [cards]);

  const onDragEnd = (result) => {
    const { draggableId, source, destination } = result;
    if (!destination) {
      return;
    }

    if (
      destination.droppableId === source.droppableId &&
      destination.index === source.index
    ) {
      return;
    }

    updateCard(draggableId, destination);
  };

  if (!isAuthenticated) {
    router.push('/users/auth');
  }

  if (loading) return <Loader />;

  if (!isAuthenticated) {
    return null;
  }

  return (
    <>
      <Head>
        <title>NEtest | Cards</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DragDropContext onDragEnd={onDragEnd}>
        <Box py={5}>
          <SimpleGrid columns={[1, 2, 4, null]} spacing={10}>
            <CardHolder
              key={0}
              id='0'
              holderCards={cards0}
              title='ON-HOLD'
              color='orange.500'
            />
            <CardHolder
              key={1}
              id='1'
              holderCards={cards1}
              title='IN-PROGRESS'
              color='blue.500'
            />
            <CardHolder
              key={2}
              id='2'
              holderCards={cards2}
              title='NEEDS-REVIEW'
              color='yellow.500'
            />
            <CardHolder
              key={3}
              id='3'
              holderCards={cards3}
              title='APPROVED'
              color='green.500'
            />
          </SimpleGrid>
        </Box>
      </DragDropContext>
    </>
  );
}
